### PR TITLE
Remove the ipc layer and replace with the multiprocessing module.

### PR DESCRIPTION
**Pull request by dvander**
Python's multiprocessing support is not super robust, and when AMBuild 2
was first written (almost seven years ago), we ran into a problem: there
was no way to multiplex across pipes. In fact, there's no way to
multiplex against anything, so the API was pretty useless. We instead
implemented IPC using some extremely brittle and hacky ctypes gunk, and
then overdesigned the abstractions involved.

It turns out that we CAN multiplex. On Windows, we can use
_winapi.WaitForMultipleObjects. Elsewhere, we can use any garden variety
select/poll implementation. This allows us to rip out all of our custom
multiprocessing code, which is what this patch does. It also greatly
simplifies the abstractions involved, and spawns one less process (the
"task master" is now the same as the root process).

Python 3 has even better multiplexing support via an explicit poll()
method in the multiprocessing module. But it doesn't support Queues,
making it very complex for us to implement a true producer/consumer (eg,
we can't have both 1:1 and 1:many channels, that I can see).

Rather than overcomplicate everything to get a true producer/consumer
flow, we retain the "push" mechanism of the original IPC design. The
flow for communication is:
 1. Processes are spawned with a bidirectional communication channel.
 2. Once spawned, the child process sends a "ready" message.
 3. The parent process will send a task once this message is received.
 4. Once a task is complete, the child is sent a new task, and any idle
    children are sent any additional tasks that can be run in parallel.
 5. Once all tasks are complete, each process is given a shutdown
    message.

### CODE REVIEW

**Comment by dvander** [comment]
This is still a WIP, needs cross-platform and edge case testing, and there are some TODOs.

**Comment by WildCard65** [comment]
@dvander If you ever need to, you can add package dependencies to AMBuild that will only be installed for certain Python versions, tidbit for you if you need it for this.

**Comment by dvander** [comment]
This turned out to be a little trickier than anticipated. Python <3.3 doesn't create I/O completion ports for Pipe objects, so there is no easy way to make them waitable. As a workaround, we now create one extra thread per process, and multiplex across threads instead. This only affects Windows on older Python versions.

Anyway, this appears to be working, after some final tests I'll merge this today.

**Comment by WildCard65** [comment]
Something to note about threading in Python if you're not aware: Only one thread is executed at a time controlled via the GIL

**Comment by dvander** [comment]
The GIL only applies to Python internal stuff, not to OS stuff. Here, we use threads for low-level polling (where the GIL, of course, does not apply), and the real computational work is being done by other processes. So contention on the global lock should be very small. The number of messages being passed is also very small.

**Comment by WildCard65** [comment]
Alrighty then.

**Comment by ErikMinekus** [comment]
ipc is still used in two places: https://github.com/alliedmodders/ambuild/search?q=ipc&unscoped_q=ipc

Currently getting:
```
Traceback (most recent call last):
  File "../configure.py", line 3, in <module>
    from ambuild2 import run
  File "/home/vagrant/.local/lib/python3.5/site-packages/ambuild2/run.py", line 21, in <module>
    from ambuild2.context import Context
  File "/home/vagrant/.local/lib/python3.5/site-packages/ambuild2/context.py", line 21, in <module>
    from ambuild2.builder import Builder
  File "/home/vagrant/.local/lib/python3.5/site-packages/ambuild2/builder.py", line 8, in <module>
    from ambuild2.task import Task, TaskMaster
  File "/home/vagrant/.local/lib/python3.5/site-packages/ambuild2/task.py", line 7, in <module>
    from ambuild2 import ipc
ImportError: cannot import name 'ipc'
```

**Pull request merged**
